import pandas as pd
import matplotlib.pyplot as plt

def generate_plot():
    # 1. Load the data generated by the test
    try:
        df = pd.read_csv("data/test_results.csv")
    except FileNotFoundError:
        print("No test data found. Run pytest first!")
        return

    # 2. Create the plot
    plt.figure(figsize=(10, 6))
    
    # Plot Set Voltage vs Measured Voltage
    plt.plot(df["Set_Voltage"], df["Set_Voltage"], 'r--', label="Reference (Ideal)")
    plt.plot(df["Set_Voltage"], df["Measured_Voltage"], 'bo-', label="Measured (Actual)")
    
    # Styling
    plt.title("Avionics Sensor Linearity Test")
    plt.xlabel("Input Voltage (V)")
    plt.ylabel("Measured Output (V)")
    plt.grid(True)
    plt.legend()
    
    # 3. Save the report
    plt.savefig("data/test_report_graph.png")
    print("Graph saved to data/test_report_graph.png")

if __name__ == "__main__":
    generate_plot()